# Generated by Django 5.0.2 on 2026-01-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código del material'),
        ),
    ]
