# Generated by Django 5.0.2 on 2026-01-31 01:06

import asistencia.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='hora',
            field=models.TimeField(default=asistencia.models.hora_actual),
        ),
    ]
