# Generated by Django 5.0.2 on 2026-03-24 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_registroasistencia_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
