# Generated by Django 5.0.2 on 2026-01-31 01:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0002_alter_proyecto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la obra')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('estado', models.CharField(choices=[('PLAN', 'Planificación'), ('PROG', 'En progreso'), ('SUSP', 'Suspendido'), ('COMP', 'Completado')], default='PLAN', max_length=4, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto')),
                ('avance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de avance')),
                ('notas', models.TextField(blank=True, verbose_name='Notas y observaciones')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='obras/', verbose_name='Foto de la obra')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('arquitecto', models.ForeignKey(blank=True, limit_choices_to={'rol': 'ARQ'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_disenadas', to=settings.AUTH_USER_MODEL, verbose_name='Arquitecto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='proyectos.proyecto', verbose_name='Proyecto asociado')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'SUP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_supervisadas', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
                ('trabajadores', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'TEC'}, related_name='obras_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Trabajadores')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
